name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    name: Installing npm dependencies
    run: npm ci
    name: Deploying using Angular CLI
    run: ng deploy --base-href=https://husam-shakeeb.github.io/srg-tech-website/