name: Build and Deploy
on:
  push:
    branches:
      - some-branch
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
       token: ${{ secrets.GH_TOKEN }}
    - run: npm ci
    - run: npx ng deploy --base-href=/srg-tech-website/ --no-silent