name: Build and Deploy
on:
  push:
    branches:
      - some-branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: git config --global user.email "mohamed-rami.mezghani@hsrw.org"
    - run: git config --global user.name "MRami153"
    - run: npx ng deploy --base-href=https://husam-shakeeb.github.io/srg-tech-website/ --no-silent