name: Build and Deploy
on:
  push:
    branches:
      - some-branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: ng add angular-cli-ghpages 
    - run: ng deploy --base-href=https://husam-shakeeb.github.io/srg-tech-website/