name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    run: npm ci
    run: npx ng deploy --base-href=https://husam-shakeeb.github.io/srg-tech-website/