name: Angular build and trigger Deploy workflow
on:
  push:
    branches:
      - master
env:
  GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: npx ng deploy --repo=https://github.com/husam-shakeeb/srg-tech-website.git --base-href=/srg-tech-website --name="SRG-Tech" --email=noreply@srg-tech.com
