name: Build and Deploy
on:
  push:
    branches:
      - some-branch
env:
  GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: npm ci
    - run: npx ng deploy --repo=https://github.com/husam-shakeeb/srg-tech-website.git --base-href=/srg-tech-website/ --name="SRG-Tech" --email=noreply@srg-tech.com
