name: Build and Deploy
on:
  push:
    branches:
      - some-branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
       token: ${{ secrets.ACCESS_TOKEN }}
    - run: git config --global user.email "mohamed-rami.mezghani@hsrw.org"   
    - run: git config --global user.name "MRami153"
    - run: npm ci
    - run: npx ng deploy --base-href=git@github.com:husam-shakeeb/srg-tech-website.git --no-silent