name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
       token: ${{ secrets.ACCESS_TOKEN }}
    - name: All things angular
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.2 ## replace by latest version without it you will see Expected format {org}/{repo}[/path]@ref. Actual 'AhsanAyaz/angular-deploy-gh-pages-actions',Input string was not in a correct format.
      with:
        github_access_token: ${{ secrets.ACCESS_TOKEN }} # see the Configuration section for how you can create secrets
        base_href: /srg-tech-website/   # make sure this corresponds to https://husam-shakeeb.github.io/srg-tech-website/
        deploy_branch: master # The branch the action should deploy to.
        angular_dist_build_folder: dist/srg-tech-website # The folder where your project is supposed to be after running ng build by the action.

